### ISSUE TITLE
Octo's Megalist of Stuff

### ISSUE THREAD

**Issue by octoshrimpy** [ceuk/spotui#24]
This is a list I compiled from small things I noticed don't quite work, or features from other TUI clients that can be imported with relative ease. None of this is final, but for other devs seeing this, if you know how to do one, please comment or send a PR. 

---

╔════════════════════
╏ todo
╚════════════════════

- [ ] nav not intuitive: tab changes panels, LR changes seekbar, UD changes cursor

- [ ] play/pause icons are inverted from what spotify has
    doesn't make sense to keep the icon there since' it's not clickable
    replace the icon with a loader (braille 4-sq spinner) when playing

- [ ] exit search with [esc]

- [ ] no padding above and below the entire app

- [ ] if "nothing is playing" is perma-visible, shouldn't search also be?
    0:0/0:0 probably shouldn't be visible if nothing is playing
    remove play bar, center "nothing is playing" vertically with the color of bar

- [ ] use elipsis character … to squeeze one more letter out of long names

- [ ] open modal with keybinds on ?

- [ ] horizontal scroll of text on long names if hovered - tracked in #23 
    https://www.youtube.com/watch?v=FGcZeVDWXR0 

- [ ] playlists capped at 50 shouldn't be a thing

- [ ] playlist folders - tracked in #21 
    https://github.com/mikez/spotify-folders

![image](https://user-images.githubusercontent.com/7097172/120235036-6d139100-c216-11eb-8a16-76fcd668c20f.png)       

- [ ] rounded corners vs square
    
![image](https://user-images.githubusercontent.com/7097172/120235058-77358f80-c216-11eb-869e-6718354bc3af.png)

- [ ] currently playing
    https://www.fileformat.info/info/unicode/block/braille_patterns/images.htm
    https://www.npmjs.com/package/cli-spinners

    or a simple icon with diff color
       ![image](https://user-images.githubusercontent.com/7097172/120235068-7dc40700-c216-11eb-8601-6eb7308eb04f.png)

![image](https://user-images.githubusercontent.com/7097172/120235076-84eb1500-c216-11eb-8b01-f16948035d91.png)

- [ ] arrow navigation for panels
    this will require two colors for borders: hovered & selected
    make playlist screen wider if focused?

- [ ] migrate next big version to blessings?
    https://github.com/erikrose/blessings

- [ ] remove delay from esc when closing popups
    https://stackoverflow.com/questions/27372068/why-does-the-escape-key-have-a-delay-in-python-curses

- [ ] remove esc as a method to close the app. (spamming esc to close menus)

- [ ] quick actions menu for those still learning/not wanting to learn keybinds
    ie: if cursor is on playlist, show playlist actions

- [ ] more steps in seekbar so it doesn't feel as jumpy, replace ░ with curses " " + bg color
    7 steps: `▏▎▍▌▋▊▉`
    2 steps:  `⠆⠶`, `⡇⡷`, `⡇⣿`, `⡁⣉`

╔════════════════════
╏ done
╚════════════════════

- [X] custom colors + theme engine - tracked in #22 
    instead, check if xterm256, and then use a custom color profile

- [X] current device icon

**Comment by octoshrimpy** [comment]
![image](https://user-images.githubusercontent.com/7097172/120252968-5df70800-c243-11eb-92ca-7b724c11ee8d.png)

Added current device to device list.

https://github.com/octoshrimpy/spotui/commit/b0c46f89ab11bf066769e83a6c1afb5cd2c9d017

**Comment by octoshrimpy** [comment]
![image](https://user-images.githubusercontent.com/7097172/120254662-91d42c80-c247-11eb-9000-492e29fffbda.png)
Added current playlist playing to playlist list. Currently it does not update on song change.
https://github.com/octoshrimpy/spotui/commit/7b667bb2b8f4bb7421b7f91574bca4c0e3d33252

**Comment by ceuk** [comment]
Hey, cheers for this - would you be able to create them as separate issues so they can be tracked easier? 

Not got time to go through properly right now but I'll categorize the above quickly into 3 categories:

1. Stuff that would make a good feature
2. That that is "meh" - i.e. can be done by someone else if they want but I'm not that interested in tracking it
3. Stuff that isn't in line with the current design philosophy

Also, rather than making all changes against master on your fork would you be able to do one branch for each issue (grouping smaller issues is cool) and raise a PR for each. Makes it easier to review/merge. I'll add a CONTRIBUTING.md at some point to define a proper process. 

## 1. Good feature candidates

* Currently playing playlist indicator
* Currently selected device indicator
* Contextual keybind hints at the top (similar to Mutt or something)
* Playlist folders
* Truncate with ellipsis char
* Hide timestamp when nothing is playing (consider hiding progress bar too)
* Escape to exit search
* Remove escape to exit app

## 2. "Nice-to-haves"

* Padding above/below
* Arrow nav for switching sections (hover not needed IMO)
* More steps in progress bar

## 3. Not in line with current design philosophy

 > nav not intuitive: tab changes panels, LR changes seekbar, UD changes cursor

The binds are modeled off a load of common GNU utils like less, vim etc. They are also in line with other modern TUI apps like [LazyGit](https://github.com/jesseduffield/lazygit). Happy to rethink the arrow keys, but the tab/j+k nav works well I think.

> arrow navigation for panels

See above

> play/pause icons are inverted from what spotify has doesn't make sense to keep the icon there since' it's not clickable replace the icon with a loader (braille 4-sq spinner) when playing

The play/pause icon is an indicator as opposed to a button. It indicates whether the track is currently playing or not (which I think it does a good job at personally)

>  migrate next big version to blessings?

Happy to consider, but there'd need to be a strong cost-benefit to introducing another dependency IMO.
